# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63cde01eff452df29e6b79c7d780de7f6adb233293ad930ccb09adba8653f7cfad39e1636ca2d67b027136129c333e94fb34126c3d040ec924151751ea5bbca8

test:
  secret_key_base: 0f20bab468cc767e2ef0c4c2d4c5a46eae6d6fb68e80aa037b7412d395e65241565b4f6fe5d0f43271f4c162bc01fe4295d4ea3e97d91b573ca7f5ba4abd0401

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
